version: '3.3'

services:
  ncds_next:
    image: node:10-alpine
    container_name: ncds_next
    working_dir: /app
    volumes:
      - ./:/app
    user: 1000:1000
    command: sh -c "yarn && yarn start"
    network_mode: host
    env_file:
      - .env
